$(function(){
	$('input').focus(function(){
		$('.hsf-two-youpin').css("display","none");
		$('.hsf-two-xinxi').css("margin-top","0.3rem");
		$('.hsf-two-continue').css("display","none");
		$('.hsf-two-continue').css("display","none");
		$('.hsf-two-next').css("display","block");
	})
})
